### ISSUE TITLE
Measuring text size

### ISSUE THREAD

**Issue by LaylBongers** [PistonDevelopers/gfx_text#25]
This is a feature required to do common things such as centering text and implementing a text box. Perhaps like this:

``` Rust
let mut text = gfx_text::new(factory).build().unwrap();
let size: [i32; 2] = text.measure("Test Value");
```

**Comment by kvark** [comment]
:+1:

**Comment by Kagami** [comment]
@LaylConway please check `measure` function in 0.5.1. See #31 for details.
