### ISSUE TITLE
Travis fails to build gfx_text with rust nightly

### ISSUE THREAD

**Issue by Kagami** [PistonDevelopers/gfx_text#27]
See e.g. https://travis-ci.org/PistonDevelopers/gfx_text/jobs/68330727

**Comment by kvark** [comment]
Looks like gfx fails on the nightly? weird

**Comment by Kagami** [comment]
But gfx itself buils without errors: https://travis-ci.org/gfx-rs/gfx

**Comment by Kagami** [comment]
@kvark seems like gfx_scene fails with same error: https://travis-ci.org/gfx-rs/gfx_scene/jobs/67940987

**Comment by Kagami** [comment]
See also: https://github.com/PistonDevelopers/conrod/issues/485

**Comment by ghost** [comment]
I have seen this locally. The exception is from Cargo itself. I did not investigate further.

**Comment by Kagami** [comment]
Upstream issue: https://github.com/rust-lang/cargo/issues/1751

**Comment by Kagami** [comment]
@csherratt are you planned to make PR from `cargo-workaround` branch? Seems like it builds on Travis without errors.

**Comment by ghost** [comment]
@Kagami oops I thought I had.

**Comment by Kagami** [comment]
Merged, thanks.
