### ISSUE TITLE
Outdated example

### ISSUE THREAD

**Issue by astahfrom** [PistonDevelopers/gfx_text#29]
Now that [gfx_window_glutin](https://github.com/gfx-rs/gfx_window_glutin) is deprecated in favour of [glutin_window](https://github.com/PistonDevelopers/glutin_window), the provided example in examples/styles.rs is out of date.
I would like to use gfx_text with the new glutin_window, but it seems to be somewhat involved?

**Comment by Kagami** [comment]
`gfx_window_glutin` crate wasn't deprecated by itself, it was only moved to the unite `gfx-rs` repo. `glutin_window` is not related to gfx, it's for piston engine.
Closing this but feel free to ask additional questions if something is still not clear.

**Comment by astahfrom** [comment]
Perfect, I just misunderstood the situation, thank you for the quick answer and this library!
