### ISSUE TITLE
Delete branch "images"

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/gfx_text#35]
It seems the "images" branch is no longer needed.

**Comment by Kagami** [comment]
It stores the screenshot from readme.

**Comment by bvssvni** [comment]
@Kagami Ok. I think you can store the image in the master branch if you want to. There are other repos doing this.

**Comment by Kagami** [comment]
Yes, probably. Separate branch is more convenient because screenshots are not that important and aren't related to the code.
