### ISSUE TITLE
Support gfx 0.9

### ISSUE THREAD

**Issue by guycook** [PistonDevelopers/gfx_text#37]
Mostly just raising this issue to let you know I've [made a start](https://github.com/guycook/gfx_text/commit/6756b7199e32d98508ed272e5dc10cbb5dd0e711) to avoid any duplicated effort

**Comment by Kagami** [comment]
Wow, a lot of changes. Thanks, I will look into it.

**Comment by kvark** [comment]
@guycook nice, thanks for staying on top of the latest and greatest!

**Comment by kvark** [comment]
Fixed by #41
