### ISSUE TITLE
gfx_text 0.13.1/0.13.0 unresolved import super::gfx using rust stable 1.13

### ISSUE THREAD

**Issue by ghost** [PistonDevelopers/gfx_text#54]
`Compiling gfx_text v0.13.1
error[E0432]: unresolved import `super::gfx`
   --> C:\Users\cube\.cargo\registry\src\github.com-1ecc6299db9ec823\gfx_text-0.13.1\src\lib.rs:567:5
    |
567 |     gfx_pipeline_base!( pipe {
    |     ^ no `gfx` in `shader_structs`
    |
    = note: this error originates in a macro outside of the current crate

error: aborting due to previous error

error: Could not compile `gfx_text`.

To learn more, run the command again with --verbose.
`

`rustc 1.13.0 (2c6933acc 2016-11-07)`

This is similar to #53 but does not seem to be the same.

**Comment by kvark** [comment]
I think https://crates.io/crates/gfx_text/0.13.2 needs to be un-yanked.

**Comment by bvssvni** [comment]
Done.

**Comment by Kagami** [comment]
I guess should be fixed now?
